/**
 * Awin connector — dual-mode.
 *
 * Awin is the first real affiliate network wired into the Deals pipeline. This
 * connector fetches offers from two sources and merges them, deduped by
 * `providerId`:
 *
 *   1. MANUAL curated layer (`AWIN_MANUAL_OFFERS`) — offers whose Awin tracking
 *      URLs were generated by hand in the Awin dashboard. Requires no secret, so
 *      it works the moment a real offer is added. Empty by default: we never
 *      fabricate an offer or a tracking URL (Kindred law: when in doubt, leave
 *      it out).
 *
 *   2. LIVE Publisher API layer — activates only when `AWIN_API_TOKEN` and
 *      `AWIN_PUBLISHER_ID` are present in the Edge Function secrets. It reads the
 *      publisher's joined programmes (merchants) and their published promotions
 *      (offers + voucher codes + tracking URLs), mapping each to a
 *      `NormalizedDeal`. No secrets → the live layer returns nothing and the
 *      connector still ships the manual layer.
 *
 * Every affiliate tracking URL — manual or live — is stored EXACTLY as provided
 * and opened verbatim after "Redeem Offer". We never rebuild it, append
 * parameters, or strip tracking.
 *
 * Awin API reference (verified 2026):
 *   • Base:        https://api.awin.com  (OAuth2 Bearer token, 20 req/min)
 *   • Programmes:  GET  /publishers/{publisherId}/programmes?relationship=joined
 *   • Offers:      POST /publisher/{publisherId}/promotions   (singular path)
 * The promotions ("Retrieve Offers") endpoint is documented but reported as
 * partial/experimental, so the live layer fails soft: any error yields an empty
 * result and the manual layer still ships.
 */
import type {
  DealScope,
  DealsFetchOptions,
  DealsSourceConnector,
  NormalizedDeal,
} from "../types.ts";

// ---------------------------------------------------------------------------
// 1. Manual curated layer
//
// Add real, hand-verified Awin offers here. Each entry must carry a genuine
// Awin tracking URL (redeemUrl) generated from the Awin dashboard. Leave empty
// until real offers exist — do not add placeholders.
// ---------------------------------------------------------------------------

export const AWIN_MANUAL_OFFERS: readonly NormalizedDeal[] = [] as const;

// ---------------------------------------------------------------------------
// 2. Live Publisher API layer
// ---------------------------------------------------------------------------

const AWIN_API_BASE = "https://api.awin.com";

/** Secrets that gate the live layer. Both must be present to call the API. */
const LIVE_ENV = ["AWIN_API_TOKEN", "AWIN_PUBLISHER_ID"] as const;

type DenoEnv = { get(key: string): string | undefined };

function denoEnv(): DenoEnv | null {
  return (globalThis as { Deno?: { env: DenoEnv } }).Deno?.env ?? null;
}

function hasLiveEnv(): boolean {
  const env = denoEnv();
  if (!env) return false;
  return LIVE_ENV.every((name) => Boolean(env.get(name)?.trim()));
}

// --- Tolerant readers for untrusted external JSON ---------------------------

function readString(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  return trimmed.length ? trimmed : null;
}

function readNumber(value: unknown): number | null {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  if (typeof value === "string" && value.trim() && Number.isFinite(Number(value))) {
    return Number(value);
  }
  return null;
}

/** First non-null string among the provided candidate keys of an object. */
function pick(obj: Record<string, unknown>, keys: string[]): string | null {
  for (const key of keys) {
    const found = readString(obj[key]);
    if (found) return found;
  }
  return null;
}

// --- Programmes (merchants) -------------------------------------------------

export type AwinProgramme = {
  id: number;
  name: string;
  primaryRegionCode: string | null;
  primarySector: string | null;
  clickThroughUrl: string | null;
};

/** Map one raw Awin programme record to the fields we use. Returns null when unusable. */
export function mapAwinProgramme(raw: unknown): AwinProgramme | null {
  if (!raw || typeof raw !== "object") return null;
  const obj = raw as Record<string, unknown>;
  const id = readNumber(obj.id);
  const name = readString(obj.name);
  if (id === null || !name) return null;
  const region = obj.primaryRegion as Record<string, unknown> | undefined;
  return {
    id,
    name,
    primaryRegionCode: region ? pick(region, ["countryCode"]) : null,
    primarySector: pick(obj, ["primarySector"]),
    clickThroughUrl: pick(obj, ["clickThroughUrl", "displayUrl"]),
  };
}

// --- Sector → Kindred category (indexed metadata, never an invented claim) --

const SECTOR_CATEGORY: Record<string, string> = {
  travel: "travel_transportation",
  "travel & leisure": "travel_transportation",
  "flights & travel": "travel_transportation",
  accommodation: "hotels_staycations",
  hotels: "hotels_staycations",
  "food & drink": "restaurants",
  restaurants: "restaurants",
  entertainment: "entertainment",
  "tickets & events": "entertainment",
  fashion: "shopping",
  "clothing & accessories": "shopping",
  retail: "shopping",
  "retail & shopping": "shopping",
  electronics: "shopping",
  home: "shopping",
  "health & beauty": "shopping",
};

/** Resolve an Awin sector string to a Kindred deal category id (safe default). */
export function categoryForSector(sector: string | null): string {
  if (!sector) return "shopping";
  return SECTOR_CATEGORY[sector.trim().toLowerCase()] ?? "shopping";
}

/** Provisional raw scope for a promotion. Travel sectors → nationwide; else online. */
function scopeForCategory(category: string): DealScope {
  if (category === "travel_transportation" || category === "hotels_staycations") {
    return "nationwide";
  }
  return "online";
}

// --- Promotions (offers) ----------------------------------------------------

/**
 * Map one raw Awin promotion into a `NormalizedDeal`, using the joined
 * programmes map to resolve the merchant name + sector. Returns null when the
 * promotion has no usable tracking URL or is missing required fields — we never
 * fabricate a redeem URL.
 *
 * Field names are read defensively (several documented spellings) because the
 * promotions payload is external, untrusted, and reported as experimental.
 */
export function mapAwinPromotionToDeal(
  raw: unknown,
  programmesById: Map<number, AwinProgramme>
): NormalizedDeal | null {
  if (!raw || typeof raw !== "object") return null;
  const obj = raw as Record<string, unknown>;

  const providerId = pick(obj, ["promotionId", "id", "offerId"]);
  const title = pick(obj, ["title", "name", "description"]);
  if (!providerId || !title) return null;

  // Tracking URL — stored verbatim, opened verbatim. No URL → not redeemable.
  const redeemUrl = pick(obj, [
    "urlTracking",
    "trackingUrl",
    "clickThroughUrl",
    "url",
    "deepLink",
  ]);
  if (!redeemUrl) return null;

  const advertiserId = readNumber(obj.advertiserId ?? obj.programmeId);
  const programme =
    advertiserId !== null ? programmesById.get(advertiserId) ?? null : null;

  const advertiserObj = obj.advertiser as Record<string, unknown> | undefined;
  const merchant =
    programme?.name ??
    (advertiserObj ? pick(advertiserObj, ["name"]) : null) ??
    pick(obj, ["advertiserName"]);
  if (!merchant) return null;

  const category = categoryForSector(programme?.primarySector ?? null);

  const voucher = obj.voucher as Record<string, unknown> | undefined;
  const voucherCode = voucher ? pick(voucher, ["code"]) : pick(obj, ["voucherCode"]);

  const description = pick(obj, ["description", "terms", "title"]) ?? title;
  const terms = pick(obj, ["terms", "termsAndConditions"]);

  return {
    provider: "awin",
    providerId,
    providerCategory: programme?.primarySector ?? null,
    scope: scopeForCategory(category),
    metroKey: null,
    category,
    merchant,
    title,
    savingsLabel: voucherCode ? "Voucher code" : "Offer",
    description,
    savingsDetail: null,
    terms,
    voucherCode,
    website: programme?.clickThroughUrl ?? null,
    redeemUrl,
    startsAt: pick(obj, ["startDate", "startsAt", "validFrom"]),
    endsAt: pick(obj, ["endDate", "endsAt", "validTo", "expires"]),
  };
}

/**
 * Request body for POST /publisher/{id}/promotions. Kept pure + exported so the
 * filter shape is unit-testable. Field names follow the Awin Offers API;
 * refine once a live 200 response is captured for the account.
 */
export function buildPromotionsBody(page: number): Record<string, unknown> {
  return {
    filters: {
      membership: "joined",
      status: "active",
      regionCodes: ["US"],
      exclusiveOnly: false,
    },
    pagination: { page, pageSize: 100 },
  };
}

async function fetchJson(
  url: string,
  init: RequestInit
): Promise<unknown | null> {
  const res = await fetch(url, init);
  if (!res.ok) {
    console.warn(`[deals:awin] ${init.method ?? "GET"} ${url} → HTTP ${res.status}`);
    return null;
  }
  return (await res.json().catch(() => null)) as unknown;
}

/** Coerce a variety of Awin list-response shapes to an array. */
function asArray(payload: unknown): unknown[] {
  if (Array.isArray(payload)) return payload;
  if (payload && typeof payload === "object") {
    const data = (payload as { data?: unknown }).data;
    if (Array.isArray(data)) return data;
  }
  return [];
}

/**
 * Live Awin fetch. Reads joined programmes, then published promotions, and maps
 * each promotion to a `NormalizedDeal`. Fails soft: any network/auth error
 * yields an empty list so the manual layer (and other connectors) are unaffected.
 */
export async function fetchAwinLive(
  _options?: DealsFetchOptions
): Promise<NormalizedDeal[]> {
  const env = denoEnv();
  const token = env?.get("AWIN_API_TOKEN")?.trim();
  const publisherId = env?.get("AWIN_PUBLISHER_ID")?.trim();
  if (!token || !publisherId) return [];

  const authHeaders = {
    Authorization: `Bearer ${token}`,
    "content-type": "application/json",
  } as const;

  try {
    // Merchants (joined programmes).
    const programmesPayload = await fetchJson(
      `${AWIN_API_BASE}/publishers/${publisherId}/programmes?relationship=joined`,
      { method: "GET", headers: authHeaders }
    );
    const programmesById = new Map<number, AwinProgramme>();
    for (const rawProgramme of asArray(programmesPayload)) {
      const programme = mapAwinProgramme(rawProgramme);
      if (programme) programmesById.set(programme.id, programme);
    }

    // Offers (promotions) — paged; capped so a runaway feed can never stall sync.
    const deals: NormalizedDeal[] = [];
    const seen = new Set<string>();
    for (let page = 1; page <= 10; page += 1) {
      const payload = await fetchJson(
        `${AWIN_API_BASE}/publisher/${publisherId}/promotions`,
        {
          method: "POST",
          headers: authHeaders,
          body: JSON.stringify(buildPromotionsBody(page)),
        }
      );
      const rows = asArray(payload);
      if (!rows.length) break;
      for (const row of rows) {
        const deal = mapAwinPromotionToDeal(row, programmesById);
        if (deal && !seen.has(deal.providerId)) {
          seen.add(deal.providerId);
          deals.push(deal);
        }
      }
      if (rows.length < 100) break;
    }
    return deals;
  } catch (err) {
    console.error("[deals:awin] live fetch failed", err);
    return [];
  }
}

// ---------------------------------------------------------------------------
// Connector factory (dual-mode)
// ---------------------------------------------------------------------------

/** Merge manual + live offers, deduped by providerId (manual wins on collision). */
function mergeOffers(
  manual: readonly NormalizedDeal[],
  live: readonly NormalizedDeal[]
): NormalizedDeal[] {
  const byId = new Map<string, NormalizedDeal>();
  for (const deal of live) byId.set(deal.providerId, deal);
  for (const deal of manual) byId.set(deal.providerId, deal); // manual overrides
  return [...byId.values()];
}

export function createAwinConnector(): DealsSourceConnector {
  const manual = AWIN_MANUAL_OFFERS;
  // Configured when there is anything to contribute: curated offers exist, or
  // the live API secrets are present. Empty manual list + no secrets → skipped.
  const configured = manual.length > 0 || hasLiveEnv();

  return {
    id: "awin",
    label: "Awin",
    trustScore: 0.8,
    isConfigured: configured,
    async fetch(options?: DealsFetchOptions): Promise<NormalizedDeal[]> {
      const live = hasLiveEnv() ? await fetchAwinLive(options) : [];
      return mergeOffers(manual, live);
    },
  };
}
