import type { HeroArtworkHoliday, HeroArtworkSeason, HeroArtworkSourceProvider } from "./types.ts";

/**
 * Curator plan for the initial ~50 museum-quality hero artworks.
 * Metadata only — no downloads, no DB rows, no UI wiring until approved.
 */
export type PlannedHeroArtwork = {
  planId: string;
  artworkTitle: string;
  artist: string;
  year: string;
  sourceInstitution: string;
  sourceProvider: HeroArtworkSourceProvider;
  /** Provider-native object id — filled when ingesting from open-access API. */
  providerArtworkId: string | null;
  tags: string[];
  seasons: HeroArtworkSeason[];
  holidays?: HeroArtworkHoliday[];
  notes?: string;
  status: "planned";
};

export const INITIAL_HERO_ARTWORK_PLAN: PlannedHeroArtwork[] = [
  { planId: "vangogh-starry-night", artworkTitle: "The Starry Night", artist: "Vincent van Gogh", year: "1889", sourceInstitution: "Museum of Modern Art (reference — verify open-access substitute)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["post_impressionism", "night", "landscape"], seasons: ["summer", "autumn"], status: "planned" },
  { planId: "monet-water-lilies", artworkTitle: "Water Lilies", artist: "Claude Monet", year: "1919", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["impressionism", "garden", "pond"], seasons: ["spring", "summer"], status: "planned" },
  { planId: "monet-impression-sunrise", artworkTitle: "Impression, Sunrise", artist: "Claude Monet", year: "1872", sourceInstitution: "Musée Marmottan Monet (verify open-access image)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["impressionism", "harbor", "sunrise"], seasons: ["spring", "summer", "autumn"], status: "planned" },
  { planId: "vermeer-girl-pearl", artworkTitle: "Girl with a Pearl Earring", artist: "Johannes Vermeer", year: "c. 1665", sourceInstitution: "Rijksmuseum", sourceProvider: "rijksmuseum", providerArtworkId: null, tags: ["dutch_golden_age", "portrait"], seasons: ["spring", "summer", "autumn", "winter"], status: "planned" },
  { planId: "rembrandt-night-watch", artworkTitle: "The Night Watch", artist: "Rembrandt", year: "1642", sourceInstitution: "Rijksmuseum", sourceProvider: "rijksmuseum", providerArtworkId: null, tags: ["dutch_golden_age", "group_portrait"], seasons: ["autumn", "winter"], status: "planned" },
  { planId: "hokusai-great-wave", artworkTitle: "The Great Wave off Kanagawa", artist: "Katsushika Hokusai", year: "c. 1831", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["ukiyo_e", "ocean", "wave"], seasons: ["summer"], status: "planned" },
  { planId: "hopper-nighthawks", artworkTitle: "Nighthawks", artist: "Edward Hopper", year: "1942", sourceInstitution: "Art Institute of Chicago", sourceProvider: "art_institute_chicago", providerArtworkId: null, tags: ["american_realism", "night", "urban"], seasons: ["autumn", "winter"], status: "planned" },
  { planId: "cassatt-mother-child", artworkTitle: "The Child's Bath", artist: "Mary Cassatt", year: "1893", sourceInstitution: "Art Institute of Chicago", sourceProvider: "art_institute_chicago", providerArtworkId: null, tags: ["impressionism", "domestic", "motherhood"], seasons: ["spring"], status: "planned" },
  { planId: "mucha-seasons-spring", artworkTitle: "The Seasons: Spring", artist: "Alphonse Mucha", year: "1896", sourceInstitution: "National Gallery of Art", sourceProvider: "national_gallery_art", providerArtworkId: null, tags: ["art_nouveau", "poster", "figure"], seasons: ["spring"], status: "planned" },
  { planId: "sargent-madame-x", artworkTitle: "Madame X (Madame Pierre Gautreau)", artist: "John Singer Sargent", year: "1883–84", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["portrait", "gilded_age"], seasons: ["winter"], status: "planned" },
  { planId: "turner-fighting-temeraire", artworkTitle: "The Fighting Temeraire", artist: "J.M.W. Turner", year: "1839", sourceInstitution: "National Gallery, London (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["romanticism", "ship", "sunset"], seasons: ["summer", "autumn"], status: "planned" },
  { planId: "okeeffe-red-canna", artworkTitle: "Red Canna", artist: "Georgia O'Keeffe", year: "1924", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["modernism", "flower", "botanical"], seasons: ["spring", "summer"], status: "planned" },
  { planId: "okeeffe-black-iris", artworkTitle: "Black Iris", artist: "Georgia O'Keeffe", year: "1926", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["modernism", "flower"], seasons: ["spring"], status: "planned" },
  { planId: "botanical-redoute-rose", artworkTitle: "Rose (Botanical study)", artist: "Pierre-Joseph Redouté", year: "c. 1800", sourceInstitution: "Library of Congress", sourceProvider: "loc", providerArtworkId: null, tags: ["botanical_illustration", "flower"], seasons: ["spring", "summer"], status: "planned" },
  { planId: "botanical-audubon-cardinal", artworkTitle: "Northern Cardinal", artist: "John James Audubon", year: "c. 1827", sourceInstitution: "National Gallery of Art", sourceProvider: "national_gallery_art", providerArtworkId: null, tags: ["natural_history", "bird"], seasons: ["winter"], status: "planned" },
  { planId: "engraving-piranesi-prisons", artworkTitle: "The Imaginary Prisons", artist: "Giovanni Battista Piranesi", year: "c. 1761", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["engraving", "architecture"], seasons: ["autumn", "winter"], status: "planned" },
  { planId: "travel-poster-wpa-national-parks", artworkTitle: "See America — National Parks", artist: "WPA Federal Art Project", year: "c. 1938", sourceInstitution: "Library of Congress", sourceProvider: "loc", providerArtworkId: null, tags: ["vintage_poster", "travel", "landscape"], seasons: ["summer"], status: "planned" },
  { planId: "historic-map-1790-us", artworkTitle: "United States Map", artist: "Unknown cartographer", year: "1790", sourceInstitution: "Library of Congress", sourceProvider: "loc", providerArtworkId: null, tags: ["historic_map", "cartography"], seasons: ["spring", "summer", "autumn", "winter"], status: "planned" },
  { planId: "degas-ballet-rehearsal", artworkTitle: "The Rehearsal", artist: "Edgar Degas", year: "c. 1874", sourceInstitution: "National Gallery of Art", sourceProvider: "national_gallery_art", providerArtworkId: null, tags: ["impressionism", "dance"], seasons: ["winter"], status: "planned" },
  { planId: "renoir-luncheon-boating", artworkTitle: "Luncheon of the Boating Party", artist: "Pierre-Auguste Renoir", year: "1881", sourceInstitution: "The Phillips Collection (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["impressionism", "social", "summer"], seasons: ["summer"], status: "planned" },
  { planId: "cezanne-mont-sainte-victoire", artworkTitle: "Mont Sainte-Victoire", artist: "Paul Cézanne", year: "1902–04", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["post_impressionism", "landscape"], seasons: ["spring", "summer"], status: "planned" },
  { planId: "gauguin-tahitian-women", artworkTitle: "Two Tahitian Women", artist: "Paul Gauguin", year: "1899", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["post_impressionism", "tropical"], seasons: ["summer"], status: "planned" },
  { planId: "whistler-nocturne", artworkTitle: "Nocturne in Blue and Gold", artist: "James McNeill Whistler", year: "1875", sourceInstitution: "Smithsonian American Art Museum", sourceProvider: "smithsonian", providerArtworkId: null, tags: ["tonalism", "night", "river"], seasons: ["autumn", "winter"], status: "planned" },
  { planId: "homage-homer-breezing-up", artworkTitle: "Breezing Up (A Fair Wind)", artist: "Winslow Homer", year: "1876", sourceInstitution: "National Gallery of Art", sourceProvider: "national_gallery_art", providerArtworkId: null, tags: ["american_realism", "sailing", "ocean"], seasons: ["summer"], status: "planned" },
  { planId: "currier-ives-winter", artworkTitle: "Central Park, Winter", artist: "Currier & Ives", year: "c. 1862", sourceInstitution: "Library of Congress", sourceProvider: "loc", providerArtworkId: null, tags: ["lithograph", "winter", "urban"], seasons: ["winter"], holidays: ["christmas", "new_year"], status: "planned" },
  { planId: "nasa-pillars-creation", artworkTitle: "Pillars of Creation", artist: "NASA / ESA / STScI", year: "1995", sourceInstitution: "NASA", sourceProvider: "nasa", providerArtworkId: null, tags: ["space", "cosmos", "photography"], seasons: ["spring", "summer", "autumn", "winter"], status: "planned" },
  { planId: "nasa-earthrise", artworkTitle: "Earthrise", artist: "NASA / William Anders", year: "1968", sourceInstitution: "NASA", sourceProvider: "nasa", providerArtworkId: null, tags: ["space", "earth"], seasons: ["spring", "summer", "autumn", "winter"], status: "planned" },
  { planId: "archives-wwii-victory", artworkTitle: "V-J Day in Times Square", artist: "Alfred Eisenstaedt (verify PD status)", year: "1945", sourceInstitution: "National Archives", sourceProvider: "national_archives", providerArtworkId: null, tags: ["documentary", "celebration"], seasons: ["summer"], holidays: ["independence_day"], notes: "Verify rights before ingest", status: "planned" },
  { planId: "hiroshige-rain-akashi", artworkTitle: "Rain Shower at Akashi", artist: "Utagawa Hiroshige", year: "c. 1833", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["ukiyo_e", "rain", "travel"], seasons: ["spring"], status: "planned" },
  { planId: "bonheur-horse-fair", artworkTitle: "The Horse Fair", artist: "Rosa Bonheur", year: "1852–55", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["realism", "animals"], seasons: ["spring", "summer"], status: "planned" },
  { planId: "morisot-cradle", artworkTitle: "The Cradle", artist: "Berthe Morisot", year: "1872", sourceInstitution: "Musée d'Orsay (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["impressionism", "domestic"], seasons: ["spring"], status: "planned" },
  { planId: "klimt-tree-life", artworkTitle: "The Tree of Life", artist: "Gustav Klimt", year: "1909", sourceInstitution: "Museum of Applied Arts, Vienna (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["art_nouveau", "pattern"], seasons: ["spring", "summer"], status: "planned" },
  { planId: "rothko-no-10", artworkTitle: "No. 10", artist: "Mark Rothko", year: "1950", sourceInstitution: "National Gallery of Art (verify rights)", sourceProvider: "national_gallery_art", providerArtworkId: null, tags: ["abstract", "color_field"], seasons: ["autumn", "winter"], notes: "Confirm copyright status — may require alternate work", status: "planned" },
  { planId: "wood-american-gothic", artworkTitle: "American Gothic", artist: "Grant Wood", year: "1930", sourceInstitution: "Art Institute of Chicago (verify rights)", sourceProvider: "art_institute_chicago", providerArtworkId: null, tags: ["regionalism", "portrait"], seasons: ["summer", "autumn"], notes: "Confirm copyright — likely not PD; swap if needed", status: "planned" },
  { planId: "church-heart-andes", artworkTitle: "Heart of the Andes", artist: "Frederic Edwin Church", year: "1859", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["hudson_river_school", "landscape", "mountain"], seasons: ["summer"], status: "planned" },
  { planId: "cole-oxbow", artworkTitle: "The Oxbow", artist: "Thomas Cole", year: "1836", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["hudson_river_school", "landscape", "river"], seasons: ["autumn"], status: "planned" },
  { planId: "bellows-polo-crowd", artworkTitle: "Polo Crowd", artist: "George Bellows", year: "1910", sourceInstitution: "National Gallery of Art", sourceProvider: "national_gallery_art", providerArtworkId: null, tags: ["ashcan_school", "sport"], seasons: ["summer"], status: "planned" },
  { planId: "stuart-washington", artworkTitle: "George Washington (Lansdowne portrait)", artist: "Gilbert Stuart", year: "1796", sourceInstitution: "National Portrait Gallery, Smithsonian", sourceProvider: "smithsonian", providerArtworkId: null, tags: ["portrait", "history"], seasons: ["summer"], holidays: ["independence_day", "memorial_day"], status: "planned" },
  { planId: "leutze-washington-crossing", artworkTitle: "Washington Crossing the Delaware", artist: "Emanuel Leutze", year: "1851", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["history", "winter"], seasons: ["winter"], holidays: ["christmas", "new_year"], status: "planned" },
  { planId: "blake-ancient-days", artworkTitle: "The Ancient of Days", artist: "William Blake", year: "1794", sourceInstitution: "British Museum (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["romanticism", "symbolism"], seasons: ["autumn", "winter"], status: "planned" },
  { planId: "friedrich-wanderer", artworkTitle: "Wanderer above the Sea of Fog", artist: "Caspar David Friedrich", year: "c. 1818", sourceInstitution: "Hamburger Kunsthalle (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["romanticism", "landscape", "fog"], seasons: ["autumn", "winter"], status: "planned" },
  { planId: "manet-luncheon-grass", artworkTitle: "Luncheon on the Grass", artist: "Édouard Manet", year: "1863", sourceInstitution: "Musée d'Orsay (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["modernism", "picnic"], seasons: ["spring", "summer"], status: "planned" },
  { planId: "seurat-sunday-afternoon", artworkTitle: "A Sunday on La Grande Jatte", artist: "Georges Seurat", year: "1884", sourceInstitution: "Art Institute of Chicago", sourceProvider: "art_institute_chicago", providerArtworkId: null, tags: ["pointillism", "park"], seasons: ["spring", "summer"], status: "planned" },
  { planId: "toulouse-lautrec-moulin", artworkTitle: "At the Moulin Rouge", artist: "Henri de Toulouse-Lautrec", year: "1892–95", sourceInstitution: "Art Institute of Chicago", sourceProvider: "art_institute_chicago", providerArtworkId: null, tags: ["post_impressionism", "nightlife"], seasons: ["autumn", "winter"], status: "planned" },
  { planId: "munch-scream", artworkTitle: "The Scream", artist: "Edvard Munch", year: "1893", sourceInstitution: "National Gallery, Oslo (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["expressionism", "anxiety"], seasons: ["autumn"], holidays: ["halloween"], notes: "Verify PD/open-access image availability", status: "planned" },
  { planId: "klimt-kiss", artworkTitle: "The Kiss", artist: "Gustav Klimt", year: "1907–08", sourceInstitution: "Österreichische Galerie Belvedere (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["art_nouveau", "romance"], seasons: ["winter"], holidays: ["valentines"], status: "planned" },
  { planId: "matisse-dance", artworkTitle: "Dance (I)", artist: "Henri Matisse", year: "1909", sourceInstitution: "Museum of Modern Art (verify open-access)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["fauvism", "movement"], seasons: ["summer"], status: "planned" },
  { planId: "picasso-old-guitarist", artworkTitle: "The Old Guitarist", artist: "Pablo Picasso", year: "1903–04", sourceInstitution: "Art Institute of Chicago", sourceProvider: "art_institute_chicago", providerArtworkId: null, tags: ["blue_period", "music"], seasons: ["autumn", "winter"], status: "planned" },
  { planId: "dali-persistence-memory", artworkTitle: "The Persistence of Memory", artist: "Salvador Dalí", year: "1931", sourceInstitution: "MoMA (verify rights — likely not PD)", sourceProvider: "wikimedia", providerArtworkId: null, tags: ["surrealism"], seasons: ["summer"], notes: "Likely requires alternate PD surrealist work", status: "planned" },
  { planId: "travel-poster-national-parks-yellowstone", artworkTitle: "Yellowstone National Park", artist: "Works Progress Administration", year: "c. 1938", sourceInstitution: "Library of Congress", sourceProvider: "loc", providerArtworkId: null, tags: ["vintage_poster", "travel", "geyser"], seasons: ["summer"], status: "planned" },
  { planId: "travel-poster-grand-canyon", artworkTitle: "Grand Canyon National Park", artist: "Works Progress Administration", year: "c. 1938", sourceInstitution: "Library of Congress", sourceProvider: "loc", providerArtworkId: null, tags: ["vintage_poster", "travel", "canyon"], seasons: ["spring", "autumn"], status: "planned" },
  { planId: "smithsonian-botanical-orchid", artworkTitle: "Orchid Botanical Study", artist: "Unknown botanical artist", year: "c. 1880", sourceInstitution: "Smithsonian Libraries", sourceProvider: "smithsonian", providerArtworkId: null, tags: ["botanical_illustration", "flower"], seasons: ["spring"], status: "planned" },
  { planId: "nga-winter-landscape-bruegel", artworkTitle: "The Harvesters", artist: "Pieter Bruegel the Elder", year: "1565", sourceInstitution: "Metropolitan Museum of Art", sourceProvider: "met", providerArtworkId: null, tags: ["northern_renaissance", "harvest"], seasons: ["summer", "autumn"], status: "planned" },
  { planId: "rijksmuseum-winter-scene-avercamp", artworkTitle: "Winter Landscape with Ice Skaters", artist: "Hendrick Avercamp", year: "c. 1608", sourceInstitution: "Rijksmuseum", sourceProvider: "rijksmuseum", providerArtworkId: null, tags: ["winter", "ice_skating"], seasons: ["winter"], holidays: ["christmas", "new_year"], status: "planned" },
];

export const INITIAL_HERO_ARTWORK_PLAN_COUNT = INITIAL_HERO_ARTWORK_PLAN.length;
