/**
 * Bandit's whispers — 8–20 words, curiosity only. Never explain. Never summarize.
 */

export const WHISPER_POOL: string[] = [
  "Psst... don't miss this one today.",
  "Psst... I'd hate for you to miss this.",
  "I'd put this near the top of today's list.",
  "This won't be around for very long now.",
  "I'd hate for you to miss this one.",
  "People wait all year for moments like this.",
  "This is one of those little seasonal moments.",
  "Sometimes the best things disappear before everyone notices.",
  "Locals usually hear about this one first, honestly.",
  "This feels like today's hidden page, I think.",
  "This one made me stop flipping pages today.",
  "Worth getting out of the house for this.",
  "Psst... don't let this week pass you by.",
  "I almost kept this one off today's paper.",
  "You didn't hear this from me, by the way.",
  "This is the kind of week that matters.",
  "I checked twice. It's worth the trip, I think.",
  "Just between us — this window is short.",
  "I had a feeling you'd want to know today.",
  "Let's keep this one between friends today, okay?",
  "I sniffed this one out before sunrise today.",
  "Don't tell everybody. Not yet, anyway, alright?",
  "This won't still be here next weekend, probably.",
  "I wouldn't wait too long on this one.",
  "Today's paper has a quiet gem in it.",
  "This is what I'd do with a free hour.",
  "The calendar says now. I'd listen to it.",
  "I keep thinking about this one today.",
  "This made me sit up a little straighter.",
  "A small thing — but the good kind.",
  "You'll know what I mean when you go.",
  "This is the week I'd mark in pencil.",
  "I flipped back to make sure I saw it right.",
  "Not loud. Not crowded. Just right for now.",
  "This is the sort of thing locals protect.",
  "I think today is the better day for this.",
  "Hard to explain. Easy to enjoy in person.",
  "This one has that limited-run feeling.",
  "I'd move this up your list for the week.",
  "The kind of moment you remember in fall.",
  "I wouldn't save this for a rainy Saturday.",
  "This feels like a today thing, honestly.",
  "You know that feeling when timing finally aligns?",
  "This is one of those before-it's-gone weeks.",
  "I paused on this page longer than most.",
  "Worth closing the laptop for, I'd say.",
  "This is what a good Tuesday can look like.",
  "I'd trade one ordinary errand for this.",
  "The season is doing something special nearby.",
  "This won't get easier to catch later on.",
  "I keep coming back to this one today.",
  "Quiet recommendation. Loud payoff, though.",
  "This is the paragraph I'd circle in pen.",
  "Not everything good announces itself loudly.",
  "I'd make a little room in the day for this.",
  "This feels like the week's honest highlight.",
  "You might thank yourself for going today.",
  "I think this is today's version of lucky.",
  "The kind of pick that ages well by Friday.",
  "This one stayed on my short list all morning.",
  "I'd rather you hear it from me than rumor.",
  "This is what Bandit would do this afternoon.",
  "A good reason to leave the house early.",
  "This has that last-chance-of-summer feel.",
  "I wouldn't bet on this waiting for you.",
  "Today's edition has a wink in it. This is it.",
  "This is the note I'd tuck into your pocket.",
  "The week gets busy. This shouldn't wait.",
  "I think you'll like how this one feels.",
  "This is one of those simple, perfect windows.",
  "I'd call this a quiet yes for today.",
  "Not famous. Not crowded. Just exactly right.",
  "This is the kind of thing worth a detour.",
  "I had to stop myself from overexplaining this.",
  "You'll see what I mean. Trust me on that.",
  "This is today's argument for going outside.",
  "I'd put real money on this being good.",
  "The paper is full. This still stood out.",
  "This feels like something you'd tell a friend.",
  "I wouldn't file this under someday.",
  "This is the week the town feels awake.",
  "A small outing. A big mood lift, maybe.",
  "I'd pencil this in before the weather turns.",
  "This one has good timing written all over it.",
  "I think your future self will nod at this.",
  "This is what I mean by a better day.",
  "Not a trend. Just a good moment nearby.",
  "I'd rather show you than describe it much.",
  "This feels like the week's gentle urgency.",
  "You know that rare when-everything-lines-up feeling?",
  "This is the line I'd read twice.",
  "I'd save your best weather for this one.",
  "This won't feel ordinary if you go today.",
  "I keep picturing this with a free afternoon.",
  "Today's list is long. This belongs near the top.",
  "This is the kind of pick that earns trust.",
  "I'd call this a soft deadline for joy.",
  "The season left a note. I think it's this.",
  "This feels like a secret the town shares.",
  "I wouldn't overthink it. Just go once.",
  "This is what I'd whisper across the table.",
  "A good week to do the thing you keep postponing.",
  "This one made the morning feel less routine.",
  "I'd rather you discover it than hear a speech.",
  "This has that gone-by-Monday energy to it.",
  "I think this is today's honest recommendation.",
  "Not flashy. Just the kind that stays with you.",
  "This is worth one early start this week.",
  "I'd bet the farm this feels right in person.",
  "Today's paper is good. This is why.",
  "This is the paragraph that earns its ink.",
  "I paused here. You might want to as well.",
  "This feels like the week to say yes.",
  "I'd move this above the usual Saturday plans.",
  "This is one of those gifts with an expiration date.",
  "I think you'll be glad you didn't scroll past.",
  "This is what I'd call a today invitation.",
  "The season is being generous. I'd accept.",
  "This won't improve by waiting until October.",
  "I had a hunch you'd want this on your radar.",
  "This is the quiet kind of special.",
  "I'd trade one screen hour for this outing.",
  "This feels like the week's best kept open secret.",
  "You know that rare right-now feeling? This is it.",
  "This is the note I'd leave on your fridge.",
  "I'd call this a soft nudge from the calendar.",
  "This one feels like it belongs in your morning.",
  "Not a headline grabber. A life improver, maybe.",
  "This is the kind of thing worth doing once.",
  "I'd put this in your today column, not later.",
  "This feels like the answer to a boring afternoon.",
  "I wouldn't wait for the perfect weekend for this.",
  "This is today's small argument for delight.",
  "I think the timing is kinder than it looks.",
  "This is what I'd call quietly unmissable.",
  "The week moves fast. This won't wait with it.",
  "I'd save this for when you need a good day.",
  "This feels like something the neighborhood already knows.",
  "I wouldn't let this season slip without one visit.",
  "This is the line that made me wag a little.",
  "I'd call this a today problem worth having.",
  "This feels like the week's most honest invitation.",
  "You might not need much convincing for this one.",
  "This is the kind of moment that rewards showing up.",
  "I'd read this twice if I were you.",
  "This won't feel like a chore. More like a gift.",
  "I think this belongs on your short walk list.",
  "This is what I'd call a gentle must-do.",
  "The calendar blinked. I think this is why.",
  "I'd rather you see it than hear me explain it.",
  "This feels like today's best small adventure.",
  "I wouldn't bookmark this for someday soon.",
  "This is the week I'd be a little spontaneous.",
  "I think you'll recognize why I flagged this.",
  "This has that last-golden-weekend feeling to it.",
  "I'd put this above another hour on the couch.",
  "This feels like the town doing something right.",
  "I wouldn't trust this to still be there in August.",
  "This is today's version of a friendly tap on the arm.",
  "I'd call this worth the extra ten minutes of driving.",
  "This feels like the season showing its best card.",
  "I think your Tuesday could use this.",
  "This is the pick I'd defend in the newsroom.",
  "I'd rather you experience it than read about it.",
  "This won't ask much of you. Just your attention.",
  "I think this is one of those rare easy wins.",
  "This feels like the week to be a little curious.",
  "I'd move this up before the heat changes everything.",
  "This is what I'd whisper if you were beside me.",
  "Not every good thing needs a billboard.",
  "This feels like today's most honest yes.",
  "I'd save a little daylight for this one.",
  "This is the kind of week that rewards saying yes.",
  "I think you'll understand once you're standing there.",
  "This won't feel like homework. Promise.",
  "I'd call this a soft highlight of the season.",
  "This feels like something worth doing before lunch.",
  "I wouldn't let the week end without considering this.",
  "This is today's gentle push toward something good.",
  "I think this belongs in your real life, not your list.",
  "This feels like the answer to what should we do.",
  "I'd trade one routine evening for this outing.",
  "This is the note I'd fold into the morning paper.",
  "I wouldn't wait for someone else to mention it first.",
  "This feels like the week's most human invitation.",
  "I think you'll be pleased you made the time.",
  "This is what I'd call a quiet little triumph.",
  "I'd put this on today's front page if I could.",
  "This won't stay subtle forever. Go while it does.",
  "I think this is the week's best small decision.",
  "This feels like something you'd regret skipping.",
  "I'd call this a today-sized adventure.",
  "This is the line I'd underline if I were you.",
  "I wouldn't overplan it. Just go once while it's here.",
  "This feels like the season being briefly generous.",
  "I think this is exactly the right week for it.",
  "This is what I'd call a friendly urgency.",
  "I'd save your best mood for this outing.",
  "This won't feel touristy. More like a local secret.",
  "I think this belongs in your better-day file.",
  "This feels like the week's most honest recommendation.",
  "I'd rather you try it once than wonder later.",
  "This is today's small gift from the calendar.",
  "I wouldn't let perfect be the enemy of this.",
  "This feels like something worth telling someone about.",
  "I think you'll like who you are after going.",
  "This is the pick I'd keep if I could only keep one.",
  "I'd call this a soft yes from the morning desk.",
  "This won't improve with more research. Just go.",
  "I think this is what today was trying to offer.",
  "This feels like the week's gentle call to action.",
  "I'd move this above the errands, honestly.",
  "This is what I'd call a worth-it Wednesday.",
  "I wouldn't wait for the crowd to find it first.",
  "This feels like the season's polite last call.",
  "I think this could make the whole day feel brighter.",
  "This is the note I'd pass across the breakfast table.",
  "I'd save this for when you need to feel alive.",
  "This won't be the loudest thing you do this week.",
  "I think it might be the most satisfying, though.",
  "This feels like today's best reason to look up.",
  "I'd call this one of those rare easy delights.",
  "This is what I'd whisper before you leave the house.",
  "I wouldn't file this under maybe later.",
  "This feels like the week to be pleasantly surprised.",
  "I think this belongs in your today, not your someday.",
  "This is the kind of pick that makes me smile.",
  "I'd put real faith in this being a good call.",
  "This won't ask for your whole day. Just a piece.",
  "I think that piece might be the best one.",
  "This feels like the answer to a gray afternoon.",
  "I'd call this today's most honest little luxury.",
  "This is what I'd save if the paper only had room for one more line.",
  "I wouldn't trust this to feel the same next month.",
  "This feels like something the week is offering on purpose.",
  "I think you'll be glad you listened to this one.",
  "This is the whisper I'd leave on your morning edition.",
  "I'd rather you go once than hear me talk about it.",
  "This won't be here when you finally feel ready.",
  "I think ready is today, for what it's worth.",
  "This feels like the week's most forgiving invitation.",
  "I'd call this a quiet yes worth taking.",
  "This is what I'd put in your hand on the way out.",
  "I wouldn't let this season end without one visit.",
  "This feels like today trying to be generous.",
  "I think this is the line you'll remember tonight.",
  "This is the pick I'd make if we were neighbors.",
  "I'd save a little wonder for this outing.",
  "This feels like a neighbor's quiet recommendation.",
  "I think that's exactly why it belongs here.",
  "This feels like the week to do something unplanned.",
  "I'd call this today's most useful little secret.",
  "This is what I'd say if you asked what not to miss.",
  "I wouldn't wait for a better excuse than right now.",
  "This feels like the season leaving the door open.",
  "I think you should walk through it once.",
  "This is the note I'd tuck under your coffee cup.",
  "I'd put this above another night of takeout and TV.",
  "This won't be ordinary if you give it an hour.",
  "I think that hour might stay with you awhile.",
  "This feels like the week's best small rebellion.",
  "I'd call this a today thing through and through.",
  "This is what I'd whisper if the room were quiet.",
  "I wouldn't overthink the timing. This is the timing.",
  "This feels like something worth doing before everyone else does.",
  "I think you'll be glad you noticed it.",
  "This is the pick that made today's paper feel alive.",
  "I'd save your best weather and your best mood for this.",
  "This won't be a story you tell forever. Just a good one.",
  "I think good ones are underrated these days.",
  "This feels like the week to collect one more memory.",
  "I'd call this today's gentle permission slip.",
  "This is what I'd say if you only read one aside.",
  "I wouldn't let the season move on without you noticing.",
  "This feels like the town being briefly wonderful.",
  "I think you should see it for yourself today.",
];

function wordCount(line: string): number {
  return line.trim().split(/\s+/).filter(Boolean).length;
}

/** Exported for tests — every whisper must stay 8–20 words. */
export function isValidWhisper(line: string): boolean {
  const n = wordCount(line);
  return n >= 8 && n <= 20;
}

function pickIndex(seed: string, length: number): number {
  let n = 0;
  for (let i = 0; i < seed.length; i++) {
    n = (n + seed.charCodeAt(i) * (i + 1)) % length;
  }
  return n;
}

export function pickBanditWhisper(input: {
  seed: string;
  recentIntros?: string[];
  avoid?: string[];
}): string {
  const pool = WHISPER_POOL.filter(isValidWhisper);
  const recent = new Set(
    (input.recentIntros ?? []).map((s) => s.trim().toLowerCase()).filter(Boolean)
  );
  const avoid = (input.avoid ?? []).map((s) => s.trim().toLowerCase()).filter(Boolean);

  const start = pickIndex(input.seed, pool.length);
  for (let offset = 0; offset < pool.length; offset++) {
    const candidate = pool[(start + offset) % pool.length];
    const key = candidate.toLowerCase();
    if (recent.has(key)) continue;
    if (avoid.some((a) => a === key || key.includes(a) || a.includes(key))) continue;
    return candidate;
  }
  return pool[start];
}
