import type { DiscoveryItem } from "./types.ts";
import { CATEGORY_FAMILY } from "./taxonomy.ts";

function item(
  partial: Omit<DiscoveryItem, "family"> & { family?: DiscoveryItem["family"] }
): DiscoveryItem {
  return {
    ...partial,
    family: partial.family ?? CATEGORY_FAMILY[partial.category],
  };
}

/**
 * Editorial seed catalog — calm, magazine-desk recommendations.
 * Location-agnostic with room for local overlays from events.
 * Providers can replace or extend this later without changing the engine.
 */
export const DISCOVERY_SEED_CATALOG: DiscoveryItem[] = [
  item({
    id: "disc_coffee_third_wave",
    title: "A quiet café worth finding",
    dek: "Look for a calm local shop with room to sit — skip the viral lists.",
    category: "coffee",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["coffee", "morning", "local", "template"],
    seasons: ["anytime"],
    weatherFit: ["any", "rainy", "cool", "fair"],
    popularity: 0.2,
    uniqueness: 0.3,
    localExpertise: 0.2,
    quality: 0.3,
  }),
  item({
    id: "disc_restaurant_neighborhood",
    title: "A neighborhood table cooking in season",
    dek: "Short menu, local produce — only when a real listing exists nearby.",
    category: "restaurants",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["dinner", "local", "seasonal", "template"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.2,
    uniqueness: 0.3,
    localExpertise: 0.2,
    quality: 0.3,
  }),
  item({
    id: "disc_recipe_weeknight",
    title: "One calm weeknight recipe",
    dek: "A trustworthy kitchen desk pick — one pan, clear steps, worth making twice.",
    category: "recipes",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["cooking", "weeknight"],
    seasons: ["anytime"],
    weatherFit: ["any", "rainy", "cool"],
    popularity: 0.55,
    uniqueness: 0.4,
    localExpertise: 0.2,
    quality: 0.95,
  }),
  item({
    id: "disc_beach_morning",
    title: "An early shoreline walk",
    dek: "Before the crowds — salt air, a clear horizon, and nowhere you have to be yet.",
    category: "beaches",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["outdoors", "morning", "weekend"],
    seasons: ["summer", "spring", "autumn"],
    weatherFit: ["fair"],
    popularity: 0.6,
    uniqueness: 0.45,
    localExpertise: 0.55,
    quality: 0.9,
  }),
  item({
    id: "disc_hike_ridge",
    title: "A ridge trail with a real view",
    dek: "Chosen for the overlook, not the step count — the view is the whole point.",
    category: "hiking",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["outdoors", "weekend", "views"],
    seasons: ["spring", "summer", "autumn"],
    weatherFit: ["fair", "cool"],
    popularity: 0.5,
    uniqueness: 0.55,
    localExpertise: 0.7,
    quality: 0.9,
  }),
  item({
    id: "disc_park_afternoon",
    title: "An afternoon in a city park",
    dek: "Shade, a bench, and room to think — the newspaper’s simplest outdoor recommendation.",
    category: "parks",
    source: { name: "Local paper", tier: "local" },
    tags: ["outdoors", "local", "quiet"],
    seasons: ["spring", "summer", "autumn"],
    weatherFit: ["fair", "cool"],
    popularity: 0.55,
    uniqueness: 0.35,
    localExpertise: 0.85,
    quality: 0.8,
  }),
  item({
    id: "disc_drive_coastal",
    title: "A short scenic drive",
    dek: "Pull-offs matter more than mileage — the good ones make you stop the car.",
    category: "scenic_drives",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["travel", "weekend", "views"],
    seasons: ["spring", "summer", "autumn"],
    weatherFit: ["fair"],
    popularity: 0.45,
    uniqueness: 0.6,
    localExpertise: 0.5,
    quality: 0.9,
  }),
  item({
    id: "disc_museum_wing",
    title: "One museum wing, unhurried",
    dek: "Skip the checklist — one room, seen properly, beats six seen in a hurry.",
    category: "museums",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["culture", "indoor", "weekend"],
    seasons: ["anytime"],
    weatherFit: ["any", "rainy", "cool"],
    popularity: 0.55,
    uniqueness: 0.5,
    localExpertise: 0.6,
    quality: 0.95,
  }),
  item({
    id: "disc_book_evening",
    title: "An evening book worth finishing",
    dek: "One title, chosen with care — not a pile you’ll never get through.",
    category: "books",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["reading", "evening"],
    seasons: ["anytime"],
    weatherFit: ["any", "rainy", "cool"],
    popularity: 0.4,
    uniqueness: 0.55,
    localExpertise: 0.15,
    quality: 0.9,
  }),
  item({
    id: "disc_movie_quiet",
    title: "A film for a quiet night in",
    dek: "Chosen for craft and mood — never a streaming dump.",
    category: "movies",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["evening", "indoor"],
    seasons: ["anytime"],
    weatherFit: ["any", "rainy", "cool"],
    popularity: 0.45,
    uniqueness: 0.5,
    localExpertise: 0.1,
    quality: 0.85,
  }),
  item({
    id: "disc_podcast_walk",
    title: "A podcast for a morning walk",
    dek: "One episode that earns the time — curious, not loud.",
    category: "podcasts",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["morning", "listening"],
    seasons: ["anytime"],
    weatherFit: ["any", "fair", "cool"],
    popularity: 0.4,
    uniqueness: 0.55,
    localExpertise: 0.1,
    quality: 0.85,
  }),
  item({
    id: "disc_hidden_side_street",
    title: "A side-street find locals keep quiet",
    dek: "Small, specific, and easy to miss — which is exactly the appeal.",
    category: "experiences",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["hidden_gem", "local", "weekend"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.25,
    uniqueness: 0.9,
    localExpertise: 0.85,
    quality: 0.9,
  }),
  item({
    id: "disc_travel_day_trip",
    title: "A near day trip with a clear reason",
    dek: "One destination, one good meal, home by evening — nothing to plan around.",
    category: "travel",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["weekend", "travel"],
    seasons: ["spring", "summer", "autumn"],
    weatherFit: ["fair", "cool"],
    popularity: 0.5,
    uniqueness: 0.55,
    localExpertise: 0.4,
    quality: 0.92,
  }),
  item({
    id: "disc_recipe_weekend_bake",
    title: "A weekend bake worth the flour",
    dek: "Technique that teaches something — not just a recipe to photograph once.",
    category: "recipes",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["cooking", "weekend"],
    seasons: ["autumn", "winter", "anytime"],
    weatherFit: ["any", "rainy", "cool"],
    popularity: 0.5,
    uniqueness: 0.45,
    localExpertise: 0.15,
    quality: 0.92,
  }),
  item({
    id: "disc_wirecutter_gear_quiet",
    title: "One well-chosen tool for the season",
    dek: "Useful, well-tested, and bought to last — never a haul.",
    category: "experiences",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["gear", "practical"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.55,
    uniqueness: 0.35,
    localExpertise: 0.1,
    quality: 0.9,
  }),

  // — Additional desk picks —
  // A single seed per category read as thin the moment local events ran dry.
  // These extend the same location-agnostic, magazine-desk voice above —
  // never a named, unverified venue — so Weekend Escapes, Bandit's Notebook,
  // and Recommendations each have real depth to draw from before a local
  // places provider exists.
  item({
    id: "disc_hike_switchback",
    title: "A switchback trail that rewards patience",
    dek: "Save your legs for the last quarter mile — the view earns it.",
    category: "hiking",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["outdoors", "weekend", "effort"],
    seasons: ["spring", "autumn"],
    weatherFit: ["fair", "cool"],
    popularity: 0.45,
    uniqueness: 0.5,
    localExpertise: 0.6,
    quality: 0.88,
  }),
  item({
    id: "disc_hike_early_light",
    title: "A trailhead worth an early alarm",
    dek: "Cooler air, softer light, and a parking spot — leave before the heat does.",
    category: "hiking",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["outdoors", "morning", "weekend"],
    seasons: ["summer", "spring"],
    weatherFit: ["fair"],
    popularity: 0.4,
    uniqueness: 0.5,
    localExpertise: 0.65,
    quality: 0.87,
  }),
  item({
    id: "disc_beach_tidepools",
    title: "A tide pool worth crouching for",
    dek: "Low tide reveals a small world most people walk right past.",
    category: "beaches",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["outdoors", "family", "weekend"],
    seasons: ["summer", "spring"],
    weatherFit: ["fair"],
    popularity: 0.4,
    uniqueness: 0.6,
    localExpertise: 0.5,
    quality: 0.85,
  }),
  item({
    id: "disc_beach_golden_hour",
    title: "The last hour of light on the water",
    dek: "Fewer people, better photographs, a reason to stay for one more song on the radio.",
    category: "beaches",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["evening", "weekend"],
    seasons: ["summer", "spring", "autumn"],
    weatherFit: ["fair"],
    popularity: 0.5,
    uniqueness: 0.5,
    localExpertise: 0.45,
    quality: 0.87,
  }),
  item({
    id: "disc_park_picnic",
    title: "A picnic table worth the extra ten minutes",
    dek: "Skip the first park you think of — the quiet one is usually better.",
    category: "parks",
    source: { name: "Local paper", tier: "local" },
    tags: ["outdoors", "family", "local"],
    seasons: ["spring", "summer", "autumn"],
    weatherFit: ["fair", "cool"],
    popularity: 0.45,
    uniqueness: 0.4,
    localExpertise: 0.8,
    quality: 0.78,
  }),
  item({
    id: "disc_park_dog_walk",
    title: "A loop built for an unhurried walk",
    dek: "Wide paths, real shade, and enough distance to actually think.",
    category: "parks",
    source: { name: "Local paper", tier: "local" },
    tags: ["outdoors", "morning", "local"],
    seasons: ["anytime"],
    weatherFit: ["fair", "cool"],
    popularity: 0.4,
    uniqueness: 0.35,
    localExpertise: 0.8,
    quality: 0.75,
  }),
  item({
    id: "disc_drive_backroad",
    title: "A backroad that beats the highway",
    dek: "Longer on the map, shorter in memory — the kind of detour worth taking.",
    category: "scenic_drives",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["travel", "weekend"],
    seasons: ["spring", "summer", "autumn"],
    weatherFit: ["fair"],
    popularity: 0.4,
    uniqueness: 0.55,
    localExpertise: 0.45,
    quality: 0.87,
  }),
  item({
    id: "disc_drive_sunset",
    title: "A drive timed for the last light",
    dek: "Leave earlier than you think — the good part is brief.",
    category: "scenic_drives",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["evening", "weekend", "views"],
    seasons: ["anytime"],
    weatherFit: ["fair"],
    popularity: 0.45,
    uniqueness: 0.5,
    localExpertise: 0.4,
    quality: 0.85,
  }),
  item({
    id: "disc_museum_small",
    title: "A small museum most people skip",
    dek: "Skip the flagship. The smaller room down the street often has the better story.",
    category: "museums",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["culture", "indoor", "local"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.35,
    uniqueness: 0.65,
    localExpertise: 0.55,
    quality: 0.88,
  }),
  item({
    id: "disc_museum_free_day",
    title: "A quiet weekday visit, not the weekend crush",
    dek: "Same collection, none of the crowd — go on the day everyone else skips.",
    category: "museums",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["culture", "indoor", "weekday"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.4,
    uniqueness: 0.5,
    localExpertise: 0.5,
    quality: 0.86,
  }),
  item({
    id: "disc_travel_overnight",
    title: "One night away, no big production",
    dek: "Pack light, stay one night, come back seeing the week differently.",
    category: "travel",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["weekend", "travel"],
    seasons: ["spring", "summer", "autumn"],
    weatherFit: ["fair", "cool"],
    popularity: 0.45,
    uniqueness: 0.5,
    localExpertise: 0.3,
    quality: 0.88,
  }),
  item({
    id: "disc_travel_town_over",
    title: "The town over that nobody bothers with",
    dek: "One good main street is sometimes all a day trip needs.",
    category: "travel",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["weekend", "travel", "hidden_gem"],
    seasons: ["anytime"],
    weatherFit: ["fair"],
    popularity: 0.3,
    uniqueness: 0.7,
    localExpertise: 0.35,
    quality: 0.85,
  }),
  item({
    id: "disc_experience_workshop",
    title: "A hands-on class worth the Saturday morning",
    dek: "Leave with something you made, not just a photo of something you saw.",
    category: "experiences",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["practical", "weekend"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.35,
    uniqueness: 0.6,
    localExpertise: 0.3,
    quality: 0.85,
  }),
  item({
    id: "disc_experience_night_market",
    title: "A night market worth wandering without a plan",
    dek: "Go hungry and follow whatever smells best — that’s the whole plan.",
    category: "experiences",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["evening", "weekend", "hidden_gem"],
    seasons: ["spring", "summer", "autumn"],
    weatherFit: ["fair"],
    popularity: 0.4,
    uniqueness: 0.7,
    localExpertise: 0.5,
    quality: 0.87,
  }),
  item({
    id: "disc_book_short_story",
    title: "A short story instead of a whole novel",
    dek: "Forty minutes, one sitting, a full arc — desk judgment on what's worth the time.",
    category: "books",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["reading", "evening"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.3,
    uniqueness: 0.5,
    localExpertise: 0.1,
    quality: 0.85,
  }),
  item({
    id: "disc_book_nonfiction",
    title: "One nonfiction book that reads like a story",
    dek: "Chosen for narrative, not homework — the kind that changes how you see something ordinary.",
    category: "books",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["reading", "curious"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.35,
    uniqueness: 0.55,
    localExpertise: 0.1,
    quality: 0.88,
  }),
  item({
    id: "disc_movie_matinee",
    title: "A matinee instead of a premiere",
    dek: "Smaller crowd, better seat, and a film that doesn't need the hype.",
    category: "movies",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["weekend", "indoor"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.3,
    uniqueness: 0.45,
    localExpertise: 0.1,
    quality: 0.8,
  }),
  item({
    id: "disc_movie_rewatch",
    title: "An old favorite worth watching again",
    dek: "Some films get better once you already know how they end.",
    category: "movies",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["evening", "indoor"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.35,
    uniqueness: 0.4,
    localExpertise: 0.1,
    quality: 0.78,
  }),
  item({
    id: "disc_podcast_longform",
    title: "A long-form episode for a longer drive",
    dek: "One story, fully told — not a highlight reel.",
    category: "podcasts",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["listening", "travel"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.3,
    uniqueness: 0.5,
    localExpertise: 0.1,
    quality: 0.82,
  }),
  item({
    id: "disc_podcast_local_voices",
    title: "A podcast about people who never usually get asked",
    dek: "Local storytelling, unhurried — the interview version of a good newspaper profile.",
    category: "podcasts",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["listening", "local"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.25,
    uniqueness: 0.6,
    localExpertise: 0.3,
    quality: 0.8,
  }),
  item({
    id: "disc_recipe_seasonal_produce",
    title: "One dish built around what's actually in season",
    dek: "Let the produce decide the menu — not the other way around.",
    category: "recipes",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["cooking", "seasonal"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.45,
    uniqueness: 0.4,
    localExpertise: 0.15,
    quality: 0.9,
  }),
  item({
    id: "disc_recipe_leftovers",
    title: "A recipe that makes yesterday's dinner better",
    dek: "A quiet specialty — the second night, done properly.",
    category: "recipes",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["cooking", "weeknight"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.5,
    uniqueness: 0.35,
    localExpertise: 0.1,
    quality: 0.88,
  }),
  item({
    id: "disc_recipe_no_recipe",
    title: "A dinner that barely needs a recipe",
    dek: "Four ingredients, one pan, and the confidence to stop measuring.",
    category: "recipes",
    source: { name: "Kindred Desk", tier: "kindred" },
    tags: ["cooking", "weeknight", "easy"],
    seasons: ["anytime"],
    weatherFit: ["any"],
    popularity: 0.4,
    uniqueness: 0.45,
    localExpertise: 0.1,
    quality: 0.85,
  }),
];

/**
 * Turn edition local events into discovery candidates.
 */
export function localEventsAsDiscoveryItems(
  events: Array<{
    name: string;
    startDateTime: string;
    venue: string;
    city: string;
    sourceUrl?: string;
    sourceName?: string;
  }>
): DiscoveryItem[] {
  return events.slice(0, 12).map((e, i) => {
    const hay = `${e.name} ${e.venue}`.toLowerCase();
    let category: DiscoveryItem["category"] = "experiences";
    if (/museum|gallery|exhibit/.test(hay)) category = "museums";
    else if (/hike|trail|walk/.test(hay)) category = "hiking";
    else if (/park|garden/.test(hay)) category = "parks";
    else if (/beach|shore|coast/.test(hay)) category = "beaches";
    else if (/coffee|cafe|café/.test(hay)) category = "coffee";
    else if (/restaurant|dinner|food|market/.test(hay)) category = "restaurants";

    const idBase = e.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .slice(0, 40);

    return item({
      id: `event_${idBase}_${i}`,
      title: e.name.trim(),
      dek: `${e.venue}${e.city ? ` · ${e.city}` : ""} — ${e.startDateTime}`,
      category,
      place: { city: e.city || null },
      source: {
        name: e.sourceName?.trim() || "Local listing",
        tier: "local",
        url: e.sourceUrl ?? null,
      },
      url: e.sourceUrl ?? null,
      tags: ["local_event", "local"],
      seasons: ["anytime"],
      weatherFit: ["any"],
      popularity: 0.4,
      uniqueness: 0.55,
      localExpertise: 0.9,
      quality: 0.7,
    });
  });
}

/** Foursquare category → Discovery Engine category. No schema changes:
 *  bookstores read naturally as a Notebook "books" find; attractions read
 *  as a Notebook "experiences" find. Coffee/restaurants/parks/museums/
 *  scenic_drives already have a matching category 1:1. */
const PLACE_CATEGORY_MAP: Record<string, DiscoveryItem["category"]> = {
  coffee: "coffee",
  restaurants: "restaurants",
  parks: "parks",
  museums: "museums",
  scenic_drives: "scenic_drives",
  bookstores: "books",
  attractions: "experiences",
};

/**
 * Verified local places (Foursquare) → discovery candidates. Every field
 * traces back to the cached provider record — Kindred never invents a
 * business, address, or fact here. `note` is Kindred's own editorial
 * voice, already written from those verified facts (see places/notes.ts),
 * never a stand-in for missing data.
 */
export function localPlacesAsDiscoveryItems(
  places: Array<{
    providerId: string;
    name: string;
    category: string;
    address: string | null;
    city: string | null;
    url: string | null;
    note?: string | null;
  }>
): DiscoveryItem[] {
  return places.map((p) => {
    const category = PLACE_CATEGORY_MAP[p.category] ?? "experiences";
    return item({
      id: `place_${p.providerId}`,
      title: p.name,
      dek:
        p.note?.trim() ||
        [p.address, p.city].filter(Boolean).join(" — ") ||
        "A local place worth a closer look.",
      category,
      place: { city: p.city ?? null },
      source: {
        name: "Foursquare",
        tier: "local",
        url: p.url ?? null,
      },
      url: p.url ?? null,
      tags: ["local_place", "verified"],
      seasons: ["anytime"],
      weatherFit: ["any"],
      popularity: 0.35,
      uniqueness: 0.4,
      localExpertise: 0.85,
      quality: 0.65,
    });
  });
}
